services:
  - type: web
    name: hrms-backend
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "gunicorn hrms.wsgi:application --chdir backend --bind 0.0.0.0:$PORT"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: hrms-db
          property: connectionString

databases:
  - name: hrms-db
    databaseName: hrms_db
    user: hrms
